# Generated by Django 4.2.1 on 2023-06-06 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_date_joined_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='railgun_address',
            field=models.CharField(blank=True, max_length=130, null=True, unique=True, validators=[django.core.validators.RegexValidator('^0zk[a-f0-9]{124}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=66, unique=True, validators=[django.core.validators.RegexValidator('^0x[a-f0-9]{40}$')]),
        ),
    ]
