# Generated by Django 4.2.1 on 2023-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_railgun_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='railgun_address',
            field=models.CharField(blank=True, max_length=130, null=True, unique=True),
        ),
    ]
